# Generated by Django 4.2.6 on 2023-11-08 07:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Domicilio', 'Domicilio'), ('Clínica', 'Clínica'), ('Videoconsulta', 'Videoconsulta')], max_length=20), size=None)),
                ('speciality', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('idioms', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Ingles', 'Ingles'), ('Español', 'Español'), ('Frances', 'Frances')], max_length=20), size=None)),
                ('years_experience', models.IntegerField()),
                ('university', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('url_map', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), size=None)),
                ('photo', models.URLField()),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Specialties',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'specialty',
            },
        ),
    ]
