# Generated by Django 4.2.6 on 2023-11-08 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppClinica', '0002_alter_doctor_idioms_alter_doctor_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='type',
            new_name='mode',
        ),
    ]
